name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install NPM deps
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: Deploy S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'
        SOURCE_DIR: 'dist'

    - name: Invalidate Cloudfront
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: './public'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
